package ec.edu.ups.p2.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2021-02-27T00:59:21.184-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "IngresarService", 
                  wsdlLocation = "http://localhost:8080/EvaluacionWSGutamaFanny/Ingresar?wsdl",
                  targetNamespace = "http://services.p2.ups.edu.ec/") 
public class IngresarService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.p2.ups.edu.ec/", "IngresarService");
    public final static QName IngresarPort = new QName("http://services.p2.ups.edu.ec/", "IngresarPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/EvaluacionWSGutamaFanny/Ingresar?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IngresarService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/EvaluacionWSGutamaFanny/Ingresar?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IngresarService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IngresarService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IngresarService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IngresarService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IngresarService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IngresarService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Ingresar
     */
    @WebEndpoint(name = "IngresarPort")
    public Ingresar getIngresarPort() {
        return super.getPort(IngresarPort, Ingresar.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ingresar
     */
    @WebEndpoint(name = "IngresarPort")
    public Ingresar getIngresarPort(WebServiceFeature... features) {
        return super.getPort(IngresarPort, Ingresar.class, features);
    }

}
