package ec.edu.ups.p2.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2021-02-27T00:59:21.173-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://services.p2.ups.edu.ec/", name = "Ingresar")
@XmlSeeAlso({ObjectFactory.class})
public interface Ingresar {

    @WebMethod
    @RequestWrapper(localName = "guardarCarrito", targetNamespace = "http://services.p2.ups.edu.ec/", className = "ec.edu.ups.p2.services.GuardarCarrito")
    @ResponseWrapper(localName = "guardarCarritoResponse", targetNamespace = "http://services.p2.ups.edu.ec/", className = "ec.edu.ups.p2.services.GuardarCarritoResponse")
    public void guardarCarrito(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "getProductos", targetNamespace = "http://services.p2.ups.edu.ec/", className = "ec.edu.ups.p2.services.GetProductos")
    @ResponseWrapper(localName = "getProductosResponse", targetNamespace = "http://services.p2.ups.edu.ec/", className = "ec.edu.ups.p2.services.GetProductosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ec.edu.ups.p2.services.Producto> getProductos() throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "guardarProductos", targetNamespace = "http://services.p2.ups.edu.ec/", className = "ec.edu.ups.p2.services.GuardarProductos")
    @ResponseWrapper(localName = "guardarProductosResponse", targetNamespace = "http://services.p2.ups.edu.ec/", className = "ec.edu.ups.p2.services.GuardarProductosResponse")
    public void guardarProductos(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );
}
